--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Jorgebyte/SystemCps
build-by-default: true
branches:
- main
projects:
  SystemCps:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/libFormsUI
        version: ^2.0.0
...
